const std = @import("std");

pub fn main(init: std.process.Init.Minimal) !void {
    const args = init.args;
    const gpa = std.heap.smp_allocator;

    if (args.vector.len < 3) {
        std.debug.print("Usage: generate-adapters <output.zig> <adapters_dir>\n", .{});
        std.process.exit(1);
    }

    const output_path = args.vector[1];
    const adapters_dir = args.vector[2];

    var dir = try std.fs.cwd().openDir(adapters_dir, .{ .iterate = true });
    defer dir.close();

    var output_file = try std.fs.cwd().createFile(output_path, .{});
    defer output_file.close();

    const writer = output_file.writer();

    try writer.writeAll("// Auto-generated by generate-adapters\n");
    try writer.writeAll("// Do not edit manually\n\n");
    try writer.writeAll("pub const AdapterEntry = struct {\n");
    try writer.writeAll("    path: []const u8,\n");
    try writer.writeAll("    content: []const u8,\n");
    try writer.writeAll("};\n\n");
    try writer.writeAll("pub const builtin_adapters = [_]AdapterEntry{\n");

    var iter = dir.iterate();
    while (try iter.next()) |entry| {
        if (entry.kind != .directory) continue;

        const site_name = entry.name;
        var site_dir = try dir.openDir(site_name, .{ .iterate = true });
        defer site_dir.close();

        var file_iter = site_dir.iterate();
        while (try file_iter.next()) |file_entry| {
            if (file_entry.kind != .file) continue;
            const ext = std.fs.path.extension(file_entry.name);
            if (!std.mem.eql(u8, ext, ".yaml")) continue;

            const file_path = try std.fs.path.join(gpa, &.{ adapters_dir, site_name, file_entry.name });
            defer gpa.free(file_path);

            const content = try std.fs.cwd().readFileAlloc(gpa, file_path, 1024 * 1024);
            defer gpa.free(content);

            const rel_path = try std.fs.path.join(gpa, &.{ site_name, file_entry.name });
            defer gpa.free(rel_path);

            try writer.writeAll("    .{\n");
            try writer.print("        .path = \"{s}\",\n", .{rel_path});
            try writer.writeAll("        .content =\n");

            // 写入多行字符串
            try writer.writeAll("        \\\"\\n");
            var lines = std.mem.splitScalar(u8, content, '\n');
            while (lines.next()) |line| {
                try writer.writeAll("        ");
                // 转义特殊字符
                for (line) |c| {
                    switch (c) {
                        '\\' => try writer.writeAll("\\\\"),
                        '"' => try writer.writeAll("\\\""),
                        else => try writer.writeByte(c),
                    }
                }
                try writer.writeAll("\n");
            }
            try writer.writeAll("        \\\",\n");
            try writer.writeAll("    },\n");
        }
    }

    try writer.writeAll("};\n");
}
